config/routes.rb
Rails.application.routes.draw do
  get 'categorization/create/:article_id/:category_id', to: "categorization#create", as: :create_categorization
  delete 'categorization/destroy/:article_id/:category_id', to: "categorization#destroy", as: :destroy_categorization
  root to: "articles#index"
  resources :articles
  resources :categories
  resources :users
  
  get "/login", to: "users#login", as: :user_login
  post "/create_session", to: "users#create_session", as: :create_session
  delete "/kill_session", to: "users#kill_session", as: :kill_session

  post "/votes/create/:user_id/:article_id/:category_id", to: "votes#create", as: :create_vote
  delete "/vote/:user_id/:article_id/:category_id", to: "votes#destroy", as: :destroy_vote
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_many :votes
  validates :title, presence: true, length: { maximum: 30 }
  validates :text, presence: true, length: { maximum: 500 }

  def text_shortened
    if text.length > 60
      "#{text[0..57]}..."
    else
      text
    end
  end
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :article
  belongs_to :category
  validate :not_twice

  private

  def not_twice
    return if Categorization.find_by(article_id: article_id, category_id: category_id).nil?

    errors.add(:article, "can't join the same category twice")
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations
  has_many :articles, through: :categorizations
  validates :name, length: { in: 2...15 }, presence: true, uniqueness: true

  def self.run_template
    create(name: 'Entertainment', priority: 2)
    create(name: 'Tech', priority: 1)
    create(name: 'Daily', priority: 3)
    create(name: 'Politics', priority: 4)
    create(name: 'Arts', priority: 6)
    create(name: 'Sports', priority: 5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :votes
  validates :name, uniqueness: true, length: { in: 2...20 }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article

  def self.most_voted_id
    find_by_sql(
      "SELECT article_id FROM votes
      GROUP BY article_id
      ORDER BY COUNT(user_id)
      DESC LIMIT 1"
    ).first.try(:article_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user, :make_categories
  def authenticate_user
    return true unless session[:current_user_id].nil?

    flash[:alert] = 'You need to be logged in to acces the website'
    redirect_to user_login_path
  end

  def make_categories
    return if Category.all.any?

    Category.run_template
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user, except: :index

  # GET /articles or /articles.json
  def index
    @categories = Category.order(:priority)
    @categories_limited = @categories.slice(0, 4)
    most_voted_id = Vote.most_voted_id
    @featured_article = if most_voted_id.nil?

                          Article.first || Article.new(title: 'Create your own article',
                                                       text: 'People at Lifestyle want to know you better!
                          Tell us your story and receive feedback from others!')
                        else
                          Article.find(most_voted_id)
                        end
  end

  def show
    @categories = Category.all
  end

  def new
    @categories = Category.order(:priority)
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'Please select a set of categories'
      redirect_to article_path(@article)
    else
      @categories = Category.order(:priority)
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :text, :user_id, :categories)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user

  # GET /categories/1 or /categories/1.json
  def show
    @categories = Category.order(:priority)
    @category = Category.find(params[:id])
    @articles = @category.articles.order('created_at DESC')
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/controllers/categorization_controller.rb
class CategorizationController < ApplicationController
  def create
    Categorization.create(article_id: params[:article_id],
                          category_id: params[:category_id])
    flash[:notice] = "Added article to #{Category.find(params[:category_id]).name}"
    article = Article.find(params[:article_id])
    article.update(image: select_image(params[:category_id].to_i))
    redirect_to article_path(params[:article_id])
  end

  def destroy
    to_delete = Categorization.find_by(article_id: params[:article_id], category_id: params[:category_id])
    to_delete.destroy
    flash[:notice] = "Removed article from #{Category.find(params[:category_id]).name}"
    redirect_to article_path(params[:article_id])
  end

  private

  def select_image(id)
    case id
    when 1
      'entertainment_bg.jpeg'
    when 2
      'tech_bg.jpg'
    when 3
      'daily_bg.jpg'
    when 4
      'politics_bg.jpeg'
    when 5
      'arts_bg.jpg'
    when 6
      'sports_bg.jpg'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user
  def login
    @user = User.new
  end

  def create_session
    @user = User.find_by(name: params[:name])
    if params[:name].empty?
      flash[:alert] = 'Insert a username'
      redirect_to user_login_path
    elsif !@user
      flash[:alert] = 'User does not exist'
      redirect_to user_login_path
    else
      session[:current_user_id] = @user.id
      flash[:notice] = "#{@user.name} Successfully logged in"
      redirect_to articles_path
    end
  end

  def kill_session
    reset_session
    flash[:notice] = 'Successfully logged out'
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      flash[:notice] = "#{@user.name} Successfully logged in"
      redirect_to articles_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user

  def create
    @vote = Vote.new(user_id: params[:user_id], article_id: params[:article_id])
    redirect_to category_path(params[:category_id]) if @vote.save
  end

  def destroy
    @vote = Vote.find_by(user_id: params[:user_id], article_id: params[:article_id])
    @vote.destroy
    redirect_to category_path(params[:category_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categorization_helper.rb
module CategorizationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/index.html.erb
<% content_for :head do %>
   <meta property="og:image" content=<%<%= image_tag "logo_size_invert.jpg" %>%>>
<% end %>
<% if flash[:notice] %>
  <p id="notice" class="container-fluid d-flex bg-success text-light justify-content-center"><%= notice %></p>
<% end %>
<nav class="container-fluid navbar row d-flex justify-space-between align-items-center nav-padding sticky-top bg-light" >
    <div class =" col-3 "> 
      <a class="nav-link" href="<%root_path%>">
        <%= image_tag "logo_size.jpg",alt: "logo", class: "logo" %>
      </a>
    </div>
    <% if  @categories.any? %>
    <div class = "col-7 d-flex">
    <%= link_to "Home", root_path, class:"nav-link orange-link" %>
      <% @categories.each do |category| %>
        <%= link_to "#{category.name}", category_path(category), class: "nav-link gray-link" %>
      <% end %>
    </div>
    <% end %>
    <div class=" col d-flex p-0 m-0">
      <% if session[:current_user_id] %>
        <%= link_to "Sign Out", kill_session_path , method: :delete, class: "nav-link 
       gray-link side-separator" %>
        
        <%= link_to 'Post', new_article_path, class: "nav-link gray-link"  %>
      <% else %>
        <%= link_to "Log in", user_login_path, class: "nav-link gray-link side-separator"  %>
        <%= link_to "Register", new_user_path, class: "nav-link gray-link"  %>
      <% end %>
    </div>
  </nav>

<% if @featured_article %>
  <div class="container-fluid d-flex flex-column bg-danger main-block m-0 justify-content-end">
    <h2 class="orange-text mx-2"><%= @featured_article.title %></h2>
    <p class="text-light mx-2"><%= @featured_article.text_shortened %></p>
      <p class ="text-light fs-6 mx-2">
      <strong>
      <% @featured_article.categories.each do |category| %> 
        <%=category.name%>/
        
      <% end %>
      </strong> 
      </p>
  </div>
<% end %>


  <div class=" container-fluid row m-0 p-0">
    <% @categories_limited.each do |category|%>
      <div class="col d-flex align-content-center secondary-block bg-<%= category.name.downcase%>">
        <h3 class="text-light category-title my-5 mx-2"><%= link_to category.name, category_path(category) , class: "inherit"%></h3>
      </div>
    <% end %>
  </div>
<footer class="container-fluid d-flex justify-space-between row bg-dark m-0">
  <div class=" col-2 h-100">
    <a class="nav-link" href="<%root_path%>">
        <%= image_tag "logo_size_invert.jpg",alt: "logo", class: "logo" %>
      </a>
  </div>
  <div class="col-7 d-flex h-100 justify-content-center">
    <a rel = "noopener noreferrer" href="#" class="orange-link footer-link"> Privacy Policy|</a>
    <a rel = "noopener noreferrer" href="#" class="orange-link footer-link"> Terms & Conditions|</a>
    <p class="text-light"> Corpyright 2021. All rights reserved</p>
  </div>
  <div class="col d-flex h-100">
    <p class="text-light w-50"> Contact us:</p>
    <ul class="list-unstyled d-flex justify-space-between h-100 w-100">
      <li><a rel = "noopener noreferrer" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm6.5 8.778c-.441.196-.916.328-1.414.388.509-.305.898-.787 1.083-1.362-.476.282-1.003.487-1.564.597-.448-.479-1.089-.778-1.796-.778-1.59 0-2.758 1.483-2.399 3.023-2.045-.103-3.86-1.083-5.074-2.572-.645 1.106-.334 2.554.762 3.287-.403-.013-.782-.124-1.114-.308-.027 1.14.791 2.207 1.975 2.445-.346.094-.726.116-1.112.042.313.978 1.224 1.689 2.3 1.709-1.037.812-2.34 1.175-3.647 1.021 1.09.699 2.383 1.106 3.773 1.106 4.572 0 7.154-3.861 6.998-7.324.482-.346.899-.78 1.229-1.274z"/></svg> </a></li>
      <li><a rel = "noopener noreferrer" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm0 7.082c1.602 0 1.792.006 2.425.035 1.627.074 2.385.845 2.46 2.459.028.633.034.822.034 2.424s-.006 1.792-.034 2.424c-.075 1.613-.832 2.386-2.46 2.46-.633.028-.822.035-2.425.035-1.602 0-1.792-.006-2.424-.035-1.63-.075-2.385-.849-2.46-2.46-.028-.632-.035-.822-.035-2.424s.007-1.792.035-2.424c.074-1.615.832-2.386 2.46-2.46.632-.029.822-.034 2.424-.034zm0-1.082c-1.63 0-1.833.007-2.474.037-2.18.1-3.39 1.309-3.49 3.489-.029.641-.036.845-.036 2.474 0 1.63.007 1.834.036 2.474.1 2.179 1.31 3.39 3.49 3.49.641.029.844.036 2.474.036 1.63 0 1.834-.007 2.475-.036 2.176-.1 3.391-1.309 3.489-3.49.029-.64.036-.844.036-2.474 0-1.629-.007-1.833-.036-2.474-.098-2.177-1.309-3.39-3.489-3.489-.641-.03-.845-.037-2.475-.037zm0 2.919c-1.701 0-3.081 1.379-3.081 3.081s1.38 3.081 3.081 3.081 3.081-1.379 3.081-3.081c0-1.701-1.38-3.081-3.081-3.081zm0 5.081c-1.105 0-2-.895-2-2 0-1.104.895-2 2-2 1.104 0 2.001.895 2.001 2s-.897 2-2.001 2zm3.202-5.922c-.397 0-.72.322-.72.72 0 .397.322.72.72.72.398 0 .721-.322.721-.72 0-.398-.322-.72-.721-.72z"/></svg></a></li>
      <li><a rel = "noopener noreferrer" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2 10h-2v2h2v6h3v-6h1.82l.18-2h-2v-.833c0-.478.096-.667.558-.667h1.442v-2.5h-2.404c-1.798 0-2.596.792-2.596 2.308v1.692z"/></svg></a></li>
    </ul>
  </div>
</footer>

app/views/articles/new.html.erb
<nav class="container-fluid navbar row d-flex justify-space-between align-items-center nav-padding sticky-top bg-light" >
    <div class =" col-3 "> 
      <a class="nav-link" href="<%root_path%>">
        <%= image_tag "logo_size.jpg",alt: "logo", class: "logo" %>
      </a>
    </div>
    <% if  @categories.any? %>
    <div class = "col-7 d-flex">
    <%= link_to "Home", root_path, class:"nav-link orange-link" %>
      <% @categories.each do |category| %>
        <%= link_to "#{category.name}", category_path(category), class: "nav-link gray-link" %>
      <% end %>
    </div>
    <% end %>
    <div class=" col d-flex p-0 m-0">
      <% if session[:current_user_id] %>
        <%= link_to "Sign Out", kill_session_path , method: :delete, class: "nav-link 
       gray-link side-separator" %>
        
        <%= link_to 'Post', new_article_path, class: "nav-link gray-link"  %>
      <% else %>
        <%= link_to "Log in", user_login_path, class: "nav-link gray-link side-separator"  %>
        <%= link_to "Register", new_user_path, class: "nav-link gray-link"  %>
      <% end %>
    </div>
  </nav>
<h1 class="orange-text mx-5">New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Home', root_path, class: "form-link mx-5" %>

<footer class="container-fluid d-flex justify-space-between row bg-dark m-0 fixed-bottom">
  <div class=" col-2 h-100">
    <a class="nav-link" href="<%root_path%>">
        <%= image_tag "logo_size_invert.jpg",alt: "logo", class: "logo" %>
      </a>
  </div>
  <div class="col-7 d-flex h-100 justify-content-center">
    <a rel = "noopener noreferrer" href="#" class="orange-link footer-link"> Privacy Policy|</a>
    <a rel = "noopener noreferrer" href="#" class="orange-link footer-link"> Terms & Conditions|</a>
    <p class="text-light"> Corpyright 2021. All rights reserved</p>
  </div>
  <div class="col d-flex h-100">
    <p class="text-light w-50"> Contact us:</p>
    <ul class="list-unstyled d-flex justify-space-between h-100 w-100">
      <li><a rel = "noopener noreferrer" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm6.5 8.778c-.441.196-.916.328-1.414.388.509-.305.898-.787 1.083-1.362-.476.282-1.003.487-1.564.597-.448-.479-1.089-.778-1.796-.778-1.59 0-2.758 1.483-2.399 3.023-2.045-.103-3.86-1.083-5.074-2.572-.645 1.106-.334 2.554.762 3.287-.403-.013-.782-.124-1.114-.308-.027 1.14.791 2.207 1.975 2.445-.346.094-.726.116-1.112.042.313.978 1.224 1.689 2.3 1.709-1.037.812-2.34 1.175-3.647 1.021 1.09.699 2.383 1.106 3.773 1.106 4.572 0 7.154-3.861 6.998-7.324.482-.346.899-.78 1.229-1.274z"/></svg> </a></li>
      <li><a rel = "noopener noreferrer" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm0 7.082c1.602 0 1.792.006 2.425.035 1.627.074 2.385.845 2.46 2.459.028.633.034.822.034 2.424s-.006 1.792-.034 2.424c-.075 1.613-.832 2.386-2.46 2.46-.633.028-.822.035-2.425.035-1.602 0-1.792-.006-2.424-.035-1.63-.075-2.385-.849-2.46-2.46-.028-.632-.035-.822-.035-2.424s.007-1.792.035-2.424c.074-1.615.832-2.386 2.46-2.46.632-.029.822-.034 2.424-.034zm0-1.082c-1.63 0-1.833.007-2.474.037-2.18.1-3.39 1.309-3.49 3.489-.029.641-.036.845-.036 2.474 0 1.63.007 1.834.036 2.474.1 2.179 1.31 3.39 3.49 3.49.641.029.844.036 2.474.036 1.63 0 1.834-.007 2.475-.036 2.176-.1 3.391-1.309 3.489-3.49.029-.64.036-.844.036-2.474 0-1.629-.007-1.833-.036-2.474-.098-2.177-1.309-3.39-3.489-3.489-.641-.03-.845-.037-2.475-.037zm0 2.919c-1.701 0-3.081 1.379-3.081 3.081s1.38 3.081 3.081 3.081 3.081-1.379 3.081-3.081c0-1.701-1.38-3.081-3.081-3.081zm0 5.081c-1.105 0-2-.895-2-2 0-1.104.895-2 2-2 1.104 0 2.001.895 2.001 2s-.897 2-2.001 2zm3.202-5.922c-.397 0-.72.322-.72.72 0 .397.322.72.72.72.398 0 .721-.322.721-.72 0-.398-.322-.72-.721-.72z"/></svg></a></li>
      <li><a rel = "noopener noreferrer" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2 10h-2v2h2v6h3v-6h1.82l.18-2h-2v-.833c0-.478.096-.667.558-.667h1.442v-2.5h-2.404c-1.798 0-2.596.792-2.596 2.308v1.692z"/></svg></a></li>
    </ul>
  </div>
</footer>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
  <% if flash[:notice]%>
    <p id="notice"><%= notice %></p>
  <% end %>
<nav class="container-fluid navbar row d-flex justify-space-between align-items-center nav-padding sticky-top bg-light" >
    <div class =" col-3 "> 
      <a class="nav-link" href="<%root_path%>">
        <%= image_tag "logo_size.jpg",alt: "logo", class: "logo" %>
      </a>
    </div>
    <% if  @categories.any? %>
    <div class = "col-7 d-flex">
    <%= link_to "Home", root_path, class:"nav-link orange-link" %>
      <% @categories.each do |category| %>
        <%= link_to "#{category.name}", category_path(category), class: "nav-link gray-link" %>
      <% end %>
    </div>
    <% end %>
    <div class=" col d-flex p-0 m-0">
      <% if session[:current_user_id] %>
        <%= link_to "Sign Out", kill_session_path , method: :delete, class: "nav-link 
       gray-link side-separator" %>
        
        <%= link_to 'Post', new_article_path, class: "nav-link gray-link"  %>
      <% else %>
        <%= link_to "Log in", user_login_path, class: "nav-link gray-link side-separator"  %>
        <%= link_to "Register", new_user_path, class: "nav-link gray-link"  %>
      <% end %>
    </div>
  </nav>

<div class="container-fluid d-flex flex-wrap">
  <% @articles.each do |art| %>
    <div class="container d-flex flex-column w-25 p-0">
    <% if (@articles.find_index{|el| el==art}).odd? %>
      <div class=" container p-0  h-50">
       <%= image_tag art.image, class: "w-100 h-100" %>
      </div>
    <% end %>
      <div div class="h-50 p-1">
        <h4 class="article-title"> <%= art.title %> </h4>
        <p><strong>By <%= art.user.name%></strong></p>
        <p> <%= art.text_shortened %></p>
        <p>
          <strong>
            <% art.categories.each do |category|%>
              <%= category.name%>/
            <% end %>
          </strong>
        </p>
        <p> <%= pluralize(art.votes.count, "vote") %></p>
        <% if Vote.find_by(user_id: session[:current_user_id], article_id: art.id) %>
          <%= link_to "unvote",destroy_vote_path(session[:current_user_id], art.id, @category.id), method: :delete, class: "gray-link fw-bold" %>
        <% else %>
          <%unless art.user_id == session[:current_user_id]%>
            <%= link_to "Vote", create_vote_path(session[:current_user_id], art.id,@category.id), method: :post, class: "gray-link fw-bold"  %>
          <% end%>
        <% end %>
      </div>
      <% if (@articles.find_index{|el| el==art}).even? %>
      <div class=" container p-0 h-50">
        <%= image_tag art.image, class: "w-100 h-100" %>
      </div>
    <% end %>
    </div>
  <% end %>
  <div class="h-0 w-25"></div>
  <div class="h-0 w-25"></div>
  <div class="h-0 w-25"></div>
  <div class="h-0 w-25"></div>
</div>

<footer class="container-fluid d-flex justify-space-between row bg-dark m-0 fixed-bottom">
  <div class=" col-2 h-100">
    <a class="nav-link" href="<%root_path%>">
        <%= image_tag "logo_size_invert.jpg",alt: "logo", class: "logo" %>
      </a>
  </div>
  <div class="col-7 d-flex h-100 justify-content-center">
    <a rel = "noopener noreferrer" href="#" class="orange-link footer-link"> Privacy Policy|</a>
    <a rel = "noopener noreferrer" href="#" class="orange-link footer-link"> Terms & Conditions|</a>
    <p class="text-light"> Corpyright 2021. All rights reserved</p>
  </div>
  <div class="col d-flex h-100">
    <p class="text-light w-50"> Contact us:</p>
    <ul class="list-unstyled d-flex justify-space-between h-100 w-100">
      <li><a rel = "noopener noreferrer" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm6.5 8.778c-.441.196-.916.328-1.414.388.509-.305.898-.787 1.083-1.362-.476.282-1.003.487-1.564.597-.448-.479-1.089-.778-1.796-.778-1.59 0-2.758 1.483-2.399 3.023-2.045-.103-3.86-1.083-5.074-2.572-.645 1.106-.334 2.554.762 3.287-.403-.013-.782-.124-1.114-.308-.027 1.14.791 2.207 1.975 2.445-.346.094-.726.116-1.112.042.313.978 1.224 1.689 2.3 1.709-1.037.812-2.34 1.175-3.647 1.021 1.09.699 2.383 1.106 3.773 1.106 4.572 0 7.154-3.861 6.998-7.324.482-.346.899-.78 1.229-1.274z"/></svg> </a></li>
      <li><a rel = "noopener noreferrer" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm0 7.082c1.602 0 1.792.006 2.425.035 1.627.074 2.385.845 2.46 2.459.028.633.034.822.034 2.424s-.006 1.792-.034 2.424c-.075 1.613-.832 2.386-2.46 2.46-.633.028-.822.035-2.425.035-1.602 0-1.792-.006-2.424-.035-1.63-.075-2.385-.849-2.46-2.46-.028-.632-.035-.822-.035-2.424s.007-1.792.035-2.424c.074-1.615.832-2.386 2.46-2.46.632-.029.822-.034 2.424-.034zm0-1.082c-1.63 0-1.833.007-2.474.037-2.18.1-3.39 1.309-3.49 3.489-.029.641-.036.845-.036 2.474 0 1.63.007 1.834.036 2.474.1 2.179 1.31 3.39 3.49 3.49.641.029.844.036 2.474.036 1.63 0 1.834-.007 2.475-.036 2.176-.1 3.391-1.309 3.489-3.49.029-.64.036-.844.036-2.474 0-1.629-.007-1.833-.036-2.474-.098-2.177-1.309-3.39-3.489-3.489-.641-.03-.845-.037-2.475-.037zm0 2.919c-1.701 0-3.081 1.379-3.081 3.081s1.38 3.081 3.081 3.081 3.081-1.379 3.081-3.081c0-1.701-1.38-3.081-3.081-3.081zm0 5.081c-1.105 0-2-.895-2-2 0-1.104.895-2 2-2 1.104 0 2.001.895 2.001 2s-.897 2-2.001 2zm3.202-5.922c-.397 0-.72.322-.72.72 0 .397.322.72.72.72.398 0 .721-.322.721-.72 0-.398-.322-.72-.721-.72z"/></svg></a></li>
      <li><a rel = "noopener noreferrer" href="#"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2c5.514 0 10 4.486 10 10s-4.486 10-10 10-10-4.486-10-10 4.486-10 10-10zm0-2c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2 10h-2v2h2v6h3v-6h1.82l.18-2h-2v-.833c0-.478.096-.667.558-.667h1.442v-2.5h-2.404c-1.798 0-2.596.792-2.596 2.308v1.692z"/></svg></a></li>
    </ul>
  </div>
</footer>